### ISSUE TITLE
news_blog 0.2.0 width news 4.1 and Typo3 7.6.2

### ISSUE THREAD

**Issue by vermillion0815** [nimius/tx_newsblog#1]
is there any workaround for news_blog 0.2.0 width news 4.1 and Typo3 7.6.2?

best regards

**Comment by pduersteler** [comment]
Hi. We're going to check this, thanks for your report!

**Comment by pduersteler** [comment]
Just tested it and it works. @vermillion0815 could you please elaborate on what exactly is not working?

**Comment by vermillion0815** [comment]
Hi,

i have no Comments-Form in Frontend, also the Autor not shown in Frontend...

best regards

**Comment by pduersteler** [comment]
Hi

tx_newsblog does not provide comments, functionality. Please have a look at https://github.com/nimius/tx_newsblog/blob/master/README.rst to see available features.

For the author problem: Also have a look at the README, as there are two ways to implement authors. If you still can't figure out how to display authors then you need to provide more information in order to get help (using abstract records, set via extmgr, or not, how you accessing it in your fluid template, etc)

**Comment by pduersteler** [comment]
Closing this issue. If you have a problem with tx_newsblog, feel free to open another one.
